version: '3'

services:
  adminer:
    image: adminer
    ports:
      - 8081:8080

  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      timeout: 10s
      retries: 10
    ports:
      - 3308:3306
  redis:
    image: redis
    ports:
      - 6379:6379